version: "3"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./web_app:/web_app
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/usr/data/db
